[project]
name = "cv"
version = "0.1.0"
description = "CV"
readme = "README.md"
site_author = "Heidi Putkuri"

[project.theme]
features = [
    "navigation.top"
]

requires-python = ">=3.12"
dependencies = [
    "zensical>=0.0.8",
]
